config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :side_dishes
  root to: "home#index"

  resources :recipes
  resources :meal_plans
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meal.rb
class Meal < ApplicationRecord
  belongs_to :meal_plan, inverse_of: :meals
  belongs_to :recipe
end

app/models/meal_plan.rb
class MealPlan < ApplicationRecord
  belongs_to :user
  has_many :meals, dependent: :destroy

  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :user, presence: true

  accepts_nested_attributes_for :meals

  scope :between, -> (start_date, end_date) { where("start_date <= ? AND end_date >= ?", start_date, end_date) }

  def to_s
    "#{start_date} - #{end_date}"
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :side_dishes

  validates :name, presence: true, uniqueness: { scope: :user_id }
  validates :description, presence: true
  validates :user, presence: true

  def to_s
    name
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipes
  has_many :meal_plans

  def recipe_options
    recipes.map do |recipe|
      [recipe.name, recipe.id]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
end

app/controllers/meal_plans_controller.rb
class MealPlansController < ApplicationController

  def index
    @current_meal_plan = current_user.meal_plans.between(Date.today, Date.today).first
    @meal_plans = current_user.meal_plans.order('start_date DESC')
  end

  def show
    @meal_plan = current_user.meal_plans.find(params[:id])
  end

  def new
    @meal_plan = current_user.meal_plans.build(
        start_date: params[:start_date] || Date.today,
        end_date: params[:end_date] || 6.days.from_now.to_date
    )

    @meal_plan.build_meals
  end

  def create
    @meal_plan = current_user.meal_plans.build(meal_plan_params)

    if @meal_plan.save
      redirect_to(meal_plan_path(@meal_plan), notice: 'Meal plan created!')
    else
      puts(@meal_plan.errors.inspect)
      @errors = @meal_plan.errors.full_messages
      render :new
    end
  end

  def edit
    @meal_plan = current_user.meal_plans.find(params[:id])
  end

  def update
    @meal_plan = current_user.meal_plans.find(params[:id])

    if @meal_plan.update(meal_plan_params)
      redirect_to(meal_plan_path(@meal_plan), notice: 'Meal plan updated!')
    else
      puts(@meal_plan.errors.inspect)
      @errors = @meal_plan.errors.full_messages
      render :edit
    end
  end

  def destroy
    @meal_plan = current_user.meal_plans.find(params[:id])
    @meal_plan.destroy
    redirect_to meal_plans_path, notice: 'Meal plan deleted!'
  end

  private

  def meal_plan_params
    params.require(:meal_plan).permit(
        :start_date,
        :end_date,
        meals_attributes: %i[
          id 
          date 
          recipe_id
        ]
    )
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
 

  def index
    @recipes = current_user.recipes.order(:id)
  end

  def show
    @recipe = current_user.recipes.find(params[:id])
  end

  def new
    @recipe = current_user.recipes.build
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)

    if @recipe.save
      redirect_to recipe_path(@recipe), notice: 'Recipe Created'
    else
      @errors = @recipe.errors.full_messages
      render :new
    end
  end

  def edit
    @recipe = current_user.recipes.find(params[:id])
  end

  def update
    @recipe = current_user.recipes.find(params[:id])

    if @recipe.update(recipe_params)
      redirect_to recipe_path(@recipe), notice: 'Recipe updated'
    else
      @errors = @recipe.errors.full_messages
      render :new
    end
  end

  def destroy
    @recipe = current_user.recipes.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path, notice: "Deleted Recipe: #{@recipe.name}"
  end


  private
  def recipe_params
    params.require(:recipe).permit(:name, :description)
  end
end

app/controllers/side_dishes_controller.rb
class SideDishesController < ApplicationController

  def index 
    @side_dishs = SideDish.all 
  end

  def show 
    @side_dish = SideDish.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/side_dishes_helper.rb
module SideDishesHelper
end

app/views/home/index.html.erb
<h1>Welcome</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wheetless</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%=javascript_pack_tag 'application', 'dta-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/meal_plans/_form.html.erb
<%= render partial: "shared/errors" %>

<%= form_for(@meal_plan) do |form| %>
  <%= form.hidden_field :start_date %>
  <%= form.hidden_field :end_date %>

  <div class="meals">
    <%= form.fields_for :meals do |meal_fields| %>
      <%= meal_fields.hidden_field :id %>
      <%= meal_fields.hidden_field :date %>
      <p><%= meal_fields.object.date.to_date %></p>

      <div class="form-control">
        <%= meal_fields.label(:recipe_id) %>
        <%= meal_fields.select(:recipe_id, current_user.recipe_options) %>
      </div>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/meal_plans/edit.html.erb
<h1>Edit Meal Plan</h1>

<%= render "form" %>

app/views/meal_plans/index.html.erb
<h1>Meal Plans</h1>

<% if @current_meal_plan.present? %>
  <h2>Current Meal Plan</h2>
  <div>
    <ul class="meals">
      <% @current_meal_plan.meals.each do |meal| %>
        <li class="meal">
          <%= meal.date.strftime('%A') %> - <%= link_to meal.recipe, recipe_path(meal.recipe) %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

<h3>All Meal Plans</h3>
<% @meal_plans.each do |meal_plan| %>
  <div class="meal_plan">
    <%= link_to meal_plan, meal_plan_path(meal_plan) %>
  </div>
<% end %>

<div class="actions">
  <%= link_to "New Meal Plan", new_meal_plan_path %>
</div>

app/views/meal_plans/new.html.erb
<h1>New Meal Plan</h1>

<%= form_for(@meal_plan, url: new_meal_plan_path, method: "GET") do |form| %>
  <div class="form-control">
    <%= form.label :start_date %>
    <%= form.text_field :start_date, type: "date" %>
  </div>

  <div class="form-control">
    <%= form.label :end_date %>
    <%= form.text_field :end_date, type: "date" %>
  </div>

  <div class="action">
    <%= form.submit("Generate Plan") %>
  </div>
<% end %>
<%= render partial: "form" %>

app/views/meal_plans/show.html.erb
<h1>Meal Plan: <%= @meal_plan %></h1>

<ul class="meals">
  <% @meal_plan.meals.each do |meal| %>
    <li class="meal">
      <%= meal.date %> - <%= link_to(meal.recipe, recipe_path(meal.recipe)) %>
    </li>
  <% end %>
</ul>


<div class="actions">
  <ul class="meal-plan-actions">
    <li><%= link_to("Edit Meal Plan", edit_meal_plan_path(@meal_plan)) %></li>
    <li><%= link_to("Delete", meal_plan_path(@meal_plan), data: {
        confirm: "Are you sure you want to delete meal plan: #{@meal_plan}?"},
        method: :delete) %></li>
    <li><%= link_to("Back to Meal Plans", meal_plans_path(@meal_plan)) %></li>
  </ul>
</div>

app/views/recipes/_form.html.erb
<% if @errors.present? %>
  <div class="errors">
    <ul>
      <% @errors.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @recipe do |form| %>
  <div class="form-group">
    <%= form.text_field :name, placeholder: "Name" %>
  </div>
  <br>
  <br>
  <div class="form-group">
    <%= form.text_area :description, placeholder: "Description" %>
  </div>
  <br>
  <br>
  <div class="actions">
    <%= form.submit %>
  </div>
  <% end %>

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>

<%= render partial: "form" %>

app/views/recipes/index.html.erb
<h1>Recipes</h1>

<div>
  <%= link_to "New Recipe", new_recipe_path %>
</div>

<div class="recipes">
  <% @recipes.each do |recipe| %>
    <div class="recipe">
      <h3><%= link_to recipe.name, recipe_path(recipe) %></h3>
      <p><%= recipe.description %></p>
      <ul class="recipe-actions">
        <li><%= link_to "Edit", edit_recipe_path(recipe) %></li>
        <li><%= link_to "Delete", recipe_path(recipe), data: {
          confirm: "Are you sure you want to delete: #{recipe.name}?",
          }, method: :delete %></li>
      </ul>
    </div>
  <% end %>
</div>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render partial: "form" %>

app/views/recipes/show.html.erb
<h1><%= @recipe.name %></h1>

<h2>Description:</h2>
<p><%= @recipe.description %></p>

<div>
  <ul class="recipe-actions">
    <li><%= link_to "Back To Recipes", recipes_path %></li>
    <li><%= link_to "Edit", edit_recipe_path(@recipe) %></li>
    <li><%= link_to "Delete", recipe_path(@recipe), data: {
      confirm: "Are you sure you want to delete: #{@recipe.name}?",
      }, method: :delete %></li>
    <li><%= link_to("Back to Meal Plans", meal_plans_path(@meal_plan)) %></li>
  </ul>
</div>

app/views/shared/_errors.html.erb
<% if @errors.present? %>
  <div class="errors">
    <ul>
      <% @errors.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Wheatless</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ms-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
        <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link" %>
      </li>
      <% else %>
       <li class="nav-item">
       <%= link_to "Register", new_user_registration_path, class: "nav-link" %>
      </li>
       <li class="nav-item">
       <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
      </li>
      <% end %>

      <li class="nav-item">
        <a class="nav-link" href="/recipes">My Recipes</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/meal_plans">My Meal Plans</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/recipes/new">New Recipe</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/side_dishes">Side Dishes</a>
      </li>
    </ul>
  </div>
</nav>

app/views/side_dishes/index.html.erb
<h1>Side Dish Page</h1>

app/views/side_dishes/show.html.erb
<%= @side_dish.name %>